import mongoose from "mongoose"

const reviewSchema = mongoose.Schema({
    user:{
        type:mongoose.Schema.Types.ObjectId, //This indicates that the user field will contain an ObjectId. ObjectId is a unique identifier generated by MongoDB for each document
        required:true,
        ref:"User", //the name of collection from where data is coming
    },
    name:{
        type:String,
        required:true,
    },
    rating:{
        type:Number,
        required:true,
    },
    comment:{
        type:String,
        required:true,
    }
},{timestamps:true,});

const productSchema =  new mongoose.Schema({
user:{
    type:mongoose.Schema.Types.ObjectId,
    required:true,
    ref:"User", //the name of collection from where data is coming
},
 name:{
    type:String,
    required:true,
 },
 image:{
    type:String,
    required:true,
 },
 category:{
    type:String,
    required:true,
 },
 description:{
    type:String,
    required:true,
 },
 reviews:[reviewSchema],
 rating:{
    type:Number,
    required:true,
    default:0,
 },
 numReviews:{
    type: Number,
    required:true,
    default:0,
 },
 price:{
    type:Number,
    required:true,
    default: 0,
 },
 countInStock:{
    type:Number,
    required:true,
    default:0,
 },
}, {timestamps: true,});

const Product = mongoose.model("Product", productSchema);

export default Product;

